#!/usr/bin/env python

import dtf.logging as log
import dtf.module as module

TAG = "TestModule"


class test_sub(module.Module):

    """Module class for viewing binary information"""

    about = 'Integration test - valid module'
    author = 'Jake Valletta (jakev)'
    name = 'test_module'
    version = '1.0.0'

    @module.sub_cmd("test")
    def cmd_test(self, args):

        log.i(TAG, "test called!")
