#!/usr/bin/env python

import dtf.logging as log

from dtf.module import Module

TAG = "TestModule"


class test_nope(Module):

    """A Module class"""

    about = 'Integration test'
    author = 'Jake Valletta (jakev)'
    name = 'test_nope'
    version = '1.0.0'

    def execute(self, args):

        """Main class executor"""

        log.i(TAG, "I was launched!")

        return 0
