#!/usr/bin/env python

import dtf.logging as log

from dtf.module import Module

TAG = "TestModule"


class test_noexecargs(Module):

    """A Module class"""

    about = 'Integration test'
    author = 'Jake Valletta (jakev)'
    health = 'stable'
    name = 'test_noexecargs'
    version = '1.0.0'
