#!/usr/bin/env bash
# Android Device Testing Framework ("dtf")
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Archive a dtf project

. dtf_core.sh
. dtf_log.sh

VERSION=1.0

usage()
{
    echo "DTF Archiver Version $VERSION"
    echo ""
    echo "Subcommands:"
    echo "    create    Archive the current project."
    echo ""
}

if [ -z "$1" ]; then
    usage
    exit -1
fi

if [ "$1" = "create" ]; then

    cd $TOP

    if [ -z "$2" ]; then 
        version_string=$(dtf prop get Info version-string)
        archive_name=${version_string}.zip
    else
        archive_name=${2}.zip
    fi
    log_i "Archiving to '${archive_name}'..."
    zip -r ${archive_name} .
else
    usage
fi
