#!/usr/bin/env bash
# Android Device Testing Framework ("dtf")
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# dtf utility for managing the dtf client

. dtf_core.sh
. dtf_log.sh

VERSION=1.0
PACKAGE_NAME=com.dtf.client
DEFAULT_PATH=/mnt/sdcard

usage()
{
    echo "dtf Client Manager Version $VERSION"
    echo ""
    echo "Subcommands:"
    echo "    install    Install the dtf client."
    echo "    status     Print the install status of the client."
    echo "    remove     Uninstall the dtf client."
    echo "    upload     Upload a file to client directory."
    echo ""
}

if [ -z "$1" ]; then
    usage
    exit -1
fi

if [ "$1" = "install" ]; then

    adb wait-for-device

    log_i "Removing old client if it exists..."
    adb uninstall ${PACKAGE_NAME} >/dev/null 2>&1

    log_i "Installing dtf client..."
    adb install ${DTF_INCLUDED}/DtfClient/dtfclient-0.0.1-signed.apk
    adb shell am startservice -a com.dtf.action.name.INITIALIZE
    dtf prop set Info busybox "/data/data/${PACKAGE_NAME}/files/busybox"
    log_i "dtf client installed."

elif [ "$1" = "remove" ]; then

    log_i "Removing dtf client..."
    adb wait-for-device
    adb uninstall $PACKAGE_NAME
    dtf prop del Info busybox
    log_i "dtf client removed."

elif [ "$1" = "status" ]; then

    installed=$(adb shell pm list packages ${PACKAGE_NAME})
    if [ -z "$installed" ]; then
        echo "dtf client Status: Not Installed"
        echo ""
    else
        echo "dtf client Status: Installed"
        echo ""
    fi

elif [ "$1"  = "upload" ]; then

    if [ -z "$2" ]; then
        echo "[ERROR] upload requires an filename."
        exit -2

    elif [ "$2" = "--path" ]; then

        if [ -z "$3" -a -z "$4" ]; then
            echo "[ERROR] upload path and file name required!"
            exit -3
        fi

        upload_path=$3
        file_name=$4

        if [ ! -f $file_name ]; then
            echo "[ERROR] File does not exist: $file_name"
            exit -4
        fi

        adb push ${file_name} "${upload_path}/" > /dev/null
        adb shell run-as ${PACKAGE_NAME} cp "${upload_path}/${file_name}" "/data/data/${PACKAGE_NAME}/"

    else
        upload_path=$DEFAULT_PATH
        file_name=$2

        if [ ! -f $file_name ]; then
            echo "[ERROR] File does not exist: $file_name"
            exit -4
        fi

        adb push ${file_name} "${upload_path}/" > /dev/null
        adb shell run-as ${PACKAGE_NAME} cp "${upload_path}/${file_name}" "/data/data/${PACKAGE_NAME}/"
    fi
fi
