#!/usr/bin/env bash
# Android Device Testing Framework ("dtf")
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DTF utility for managing the DTF Client

. dtf_core.sh
. dtf_log.sh

VERSION=1.0
PACKAGE_NAME=com.dtf.client

usage()
{
    echo "DTF Client Manager Version $VERSION"
    echo ""
    echo "Subcommands:"
    echo "    install    Install the DTF client."
    echo "    remove     Uninstall the DTF client."
    echo ""
}

if [ -z "$1" ]; then
    usage
    exit -1
fi

if [ "$1" = "install" ]; then

    adb wait-for-device

    log_i "Removing old client if it exists..."
    adb uninstall ${PACKAGE_NAME} >/dev/null 2>&1

    log_i "Installing DTF Client..."
    adb install ${DTF_INCLUDED}/DtfClient/dtfclient-0.0.1-signed.apk
    adb shell am startservice -a com.dtf.action.name.INITIALIZE
    dtf prop set Info busybox "/data/data/${PACKAGE_NAME}/files/busybox"
    log_i "DTF Client installed."

elif [ "$1" = "remove" ]; then
    log_i "Removing DTF Client..."
    adb wait-for-device
    adb uninstall $PACKAGE_NAME
    dtf prop del Info busybox
    log_i "DTF Client removed."
fi
