#!/usr/bin/env bash
# Android Device Testing Framework ("dtf")
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DTF Initialization script. 
. dtf_log.sh

# Override printing to stdout
LOG_TO_STDOUT=0

abort()
{
    echo "Exiting DTF initialization!!" 1>&2
    rm .dtfini 2> /dev/null
    rm .dtflog 2> /dev/null
    exit -4
}

echo "Initializing dtf directory..."

log_i "Project initialization started."

if [ -e .dtfini ]; then
    echo "[ERROR] Configuration already exists!"
    log_e "Project configuration already exists, failing."
    exit -1
fi

# DTF is going to try to help us setting a serial, but it doesnt exist yet (which breaks the adb wait).
# We're going to blow it away for now. 
unset ANDROID_SERIAL

# Sometimes there are errors, and we need to bail.  We'll remove the (protentially) incomplete .dtfini.
trap abort 1 2 15

echo -n "Please connect the test device (press Enter to continue) "
read _

echo "Restarting ADB..."
adb kill-server && adb start-server -a > /dev/null

echo "Waiting for a device to be connected..."
# We can't use `adb wait-for-device`, so just sleep for a second.
sleep 1

IFS=$'\r\n' GLOBIGNORE='*' :; devices=($(adb devices | grep -E "device$" |awk '{print $1}'))

if [ ${#devices[@]} = "0" ]; then
    echo "[ERROR] No devices found, exiting!"
    exit -2

elif [ ${#devices[@]} = "1" ]; then
    echo -n "Got serial ${devices}, is this correct? [Y/n] "
    read res

    if [ "$res" = "n" ]; then
        echo "Bailing!"
        exit -3
    fi

    serial=${devices}

elif [[ ${#devices[@]} -gt 1 ]]; then

    echo "Found many devices. Please select from the following list:"
    i=0
    for device in "${devices[@]}"; do
        echo "#${i}. ${device}"
        i=$((i+1))
    done

    echo ""
    echo -n "Which device #? "
    read val

    # Is it valid input?
    i=0
    for _ in  "${devices[@]}"; do
        if [ "$val" = $i ]; then
            serial=${devices[$i]}
        fi
        i=$((i+1))
    done

    if [ -z $serial ]; then
        echo "[ERROR] In valid input: '${val}'"
        exit -4
    fi
fi

echo "Preparing device: ${serial}"

touch .dtfini

# Start setting properties
dtf prop set Info serial "${serial}"

# Get the kernel
kernel=$(dtf shell "cat /proc/version")

dtf prop set Info kernel "${kernel}"

# Get the SDK version
sdk=$(dtf shell getprop ro.build.version.sdk|sed 's/\r//')

dtf prop set Info SDK "${sdk}"

# Set path
path=$(dtf shell set |grep -E "^PATH" | sed 's/^PATH\=//g')
dtf prop set Info path "${path}"

# Set bootclasspath
bcp=$(dtf shell set |grep -E "^BOOTCLASSPATH" | sed 's/^BOOTCLASSPATH\=//g')
dtf prop set Info bootclasspath-jars "${bcp}"

# Get versioning info.
brand=$(dtf shell getprop ro.product.brand|sed 's/\r//')
name=$(dtf shell getprop ro.product.name|sed 's/\r//')
version=$(dtf shell getprop ro.build.id|sed 's/\r//')
version_string=${brand}-${name}_${version}

echo "dtf would like to use following version string:"
echo ""
echo $version_string
echo ""
echo -n "Would you like to change it? [N/y] "

read res

if [ "$res" == "y" -o "$res" == "Y" ]; then
    echo -n "Please enter a custom version string: "
    read version
    echo "Using version string '${version}'..."
    dtf prop set Info version-string "${version}"
else
   dtf prop set Info version-string "${version_string}"
fi

# Determine if ARM or ARM64
arch=$(dtf shell getprop ro.product.cpu.abi|sed 's/\r//')

if [ -z $arch ]; then
    echo "[ERROR] Unable to determine processor architecture. Exiting."
    abort
fi

# 32-bits
if [[ "$arch" == "armeabi"* ]]; then
    dtf prop set Info cpu-bits "32"
# 64-bits
elif [[ "$arch" == "arm"*"64"* ]]; then
    dtf prop set Info cpu-bits "64"
# Not sure.
else
    echo "[ERROR] Unsupported CPU architecture: ${arch}"
    abort
fi

# Getting the VM type doesn't seem consistent.

# ART was introduced in KitKat, so if we're less than that, Dalvik.
if [ $sdk -lt 20 ]; then
    vmtype="Dalvik"

# If there is a single "persist.sys.dalvik.vm.lib", use it!
elif [ $(dtf shell getprop |grep persist.sys.dalvik.vm.lib|sed 's/\r//'|wc -l) = 1 ]; then

    if [ "$(dtf shell getprop |grep persist.sys.dalvik.vm.lib|sed 's/\r//'|awk '{print $2}')" = "[libart.so]" ]; then
        vmtype="ART"
    else
        vmtype="Dalvik"
    fi

# There are two values.  Check for the "arm" directory in frameworks. [HACK]
else

    cpu_bits=$(dtf prop get Info cpu-bits)
    if [ "$cpu_bits" = "64" ]; then
        arm_dir=/system/framework/arm
    else
        arm_dir=/system/framework/arm64
    fi

    if [[ "$(dtf shell ls ${arm_dir}|sed 's/\r//')" =~ "No such file or directory" ]]; then
        vmtype="Dalvik"
    else
        vmtype="ART"
    fi
fi

log_d "Using VM Type of '${vmtype}'"
dtf prop set Info vmtype "${vmtype}"

# Set the "Local variables"
mkdir reports 2>/dev/null
mkdir .dbs 2>/dev/null
mkdir local_modules 2>/dev/null

dtf prop set Local reports-dir "reports"
dtf prop set Local db-dir ".dbs"

# Install the DTF Client. It's really lightweight.
dtf client install

log_i "Project initialization complete!"
