#!/usr/bin/env bash
# Android Device Testing Framework ("dtf")
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prints local modules.

cd $TOP

IFS=$'\n'

pad=$(printf '%0.1s' " "{1..60})
padlength=30

echo "Local Modules:"
for file in `ls ./local_modules 2>/dev/null`; do

    help_string=$(grep -r "#@About:" ./local_modules/${file}|sed 's/^.*#@About: //g')

    printf '  %s' "$file"
    printf '%*.*s' 0 $((padlength - ${#file} )) "$pad"
    printf '%s\n' "$help_string"
done

echo ""
