#!/usr/bin/env bash
# Android Device Testing Framework ("dtf")
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DTF module printer.

. dtf_core.sh

DTF_DB=${DTF_DIR}/main.db

IFS=$'\n'

pad=$(printf '%0.1s' " "{1..60})
padlength=30

do_normal()
{
    echo "Installed Global Modules:"
    sql="SELECT m.name,m.about
         FROM modules m 
         ORDER BY m.name"

    ORIG_IFS=$IFS        # Save the original IFS
    LINE_IFS=$'\n'$'\r'  # For splitting input into lines
    FIELD_IFS=\|         # For splitting lines into fields

    results=$(sqlite3 "${DTF_DB}" "${sql}" 2> /dev/null)

    IFS=$LINE_IFS
    for LINE in $results; do
        IFS=$FIELD_IFS
        FIELDS=($LINE)
        IFS=$LINE_IFS

        name=${FIELDS[0]}
        about=${FIELDS[1]}

        printf '  %s' "$name"
        printf '%*.*s' 0 $((padlength - ${#name} )) "$pad"
        printf '%s\n' "$about"
       
    done
}

do_normal 
