#!/usr/bin/env bash
# Android Device Testing Framework ("dtf")
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DTF Package manager launcher

# Components are as follows:
#   modules ($DTF/modules/)
#       Modules should be shell scripts, or links to binary/scripted content.  They may use bins, packages, and libs 
#       perform their task.
#   binaries $DTF/bin/
#       Binaries (doesn't need to be C) exist to help modules perform their task.
#   packages $DTF/packages/
#       Packages are general storage.
#   libraries $DTF/lib/
#       Libraries are additional Python code you would like to be sourced for modules.

. dtf_core.sh

${DTF_DIR}/dtf_package_manager.py $@
