#!/usr/bin/env bash
# Android Device Testing Framework ("dtf")
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Get the status of your device.

if [ ! -f .dtfini ]; then
    echo "[ERROR] No configuration file found. Are you sure a project exists here?"
    exit -1
fi

serial=$(dtf prop get Info serial)

rtn=$(adb devices |grep ${serial}|awk '{print $2}')

echo ""
if [ "$rtn" != "" ]; then
   status="Connected (${rtn})"
else
   status="Not Connected"
fi

echo "  Status: ${status}"

echo "  Serial Number: ${serial}"
